datasources:
  default:
    connection:
      url: ${MONGO_URL}
public:
  cfs:
    store: "local"
    local: 
      folder: "./storage"
  accounts:
    is_username_skip_minrequiredlength: true
email:
  host:
  port: 465
  username:
  password:
  secure: true
  from:
tenant:
  _id:
  name: 华炎魔方
  logo_url:
  background_url: 
  enable_register: true
  enable_forget_password: false
  enable_create_tenant: true
  enable_password_login: true
  enable_bind_email: false
  enable_bind_mobile: false
cron:
  instancerecordqueue_interval: 10000
plugins:
  - "@steedos/accounts"
  - "@steedos/app-oa"
  - "@steedos/metadata-api"
  - "@steedos/plugin-enterprise"