datasources:
  default:
    connection:
      url: ${MONGO_URL}
public:
  cfs:
    store: "local"
    local: 
      folder: "./storage"
email:
  host:
  port: 465
  username:
  password:
  secure: true
  from:
tenant:
  _id:
  name: 华炎魔方
  logo_url:
  background_url: 
  enable_register: true
  enable_forget_password: false
  enable_create_tenant: true
  enable_password_login: true
  enable_bind_email: false
  enable_bind_mobile: false
cron:
#  statistics: 0 0 0 * * *
#  mailqueue_interval: 1000
#  push_interval: 1000
#  calendar_dav_interval: 30000
  calendar_remind: 60000
#  webhookqueue_interval: 1000
  instancerecordqueue_interval: 10000
#  objectwebhooksqueue_interval: 10000
plugins:
  - "@steedos/accounts"
  - "@steedos/metadata-api"
  - "@steedos/word-template"
  - "@steedos/plugin-enterprise"